import { uniqueId } from "@utils/unique";


export interface ArticleInput {
  title: string;
  description: string;
  body: string;
  tagList: string[];
}

export function articleData(overrides: Partial<ArticleInput> = {}): ArticleInput {
  return {
    title: `Test Article ${uniqueId()}`,
    description: "Generated by the article factory",
    body: "Article body for automated tests.",
    tagList: [],                 // required by the API (Chapter 13)
    ...overrides,                // anything the caller passed wins
  };
}
